# Generated by Django 4.1.3 on 2022-11-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=40)),
                ('caracteristicas_empresa', models.TextField()),
            ],
        ),
    ]
